name: Common Steps

runs:
  using: 'composite'
  steps:
  - name: Upload coverage report to workflow run page
    uses: actions/upload-artifact@v4  # see https://github.com/actions/upload-artifact
    with:
      name: coverage-${{ github.job }}
      overwrite: true
      include-hidden-files: true
      path: |
        htmlcov
        coverage_report.txt
        .coverage
        badges
