# Copyright 2024 Wolfgang Hoschek AT mac DOT com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Test on AlmaLinux via Lima
description: Run tests via Lima in an AlmaLinux VM with a chosen ZFS version

inputs:
  alma_major_version:
    description: AlmaLinux major version (for example "9" or "10")
    required: true
  zfs_version:
    description: ZFS repo name (for example "zfs-2.2", "zfs-2.3", "zfs-2.4")
    required: true
  ssh_program:
    description: SSH binary name to test with ("ssh" or "hpnssh")
    required: true

runs:
  using: composite
  steps:
    - name: Set up Lima
      uses: lima-vm/lima-actions/setup@55627e31b78637bf254a8b2a14da8ea7d12564e5 # aka v1.1.0; see https://github.com/lima-vm/lima-actions
      with: # or manually install via `brew install lima` or equivalent
        version: "v2.1.4"
    - name: Start VM via Lima
      shell: bash
      env:
        LIMA_VM_NAME: mylimavm
        LIMA_VM_TEMPLATE: "template:almalinux-${{ inputs.alma_major_version }}"
        LIMA_VM_MOUNT_TYPE: reverse-sshfs
        LIMA_WORKDIR_WRITABLE: "true"
        LIMA_NO_RUN_TESTS: "true"
        LIMA_ZFS_VERSION: ${{ inputs.zfs_version }}
        LIMA_SSH_PROGRAM: ${{ inputs.ssh_program }}
        LIMA_START_TIMEOUT: 3m
      run: |
        limactl --version
        bzfs_testbed/lima_vm.sh
    - name: Run tests inside VM
      shell: bash
      env:
        ssh_program: ${{ inputs.ssh_program }}
      run: |
        limactl shell --workdir=/bzfs mylimavm -- env \
          bzfs_test_mode="$bzfs_test_mode" \
          bzfs_test_no_run_quietly="$bzfs_test_no_run_quietly" \
          bzfs_test_ssh_program="$ssh_program" \
          bash -lc './test.sh && PYTHONPATH=. .github-workflow-scripts/generate_badges.py generate'
        echo "bzfs-testrun-success"
