#!/usr/bin/env bash
#
# Copyright 2024 Wolfgang Hoschek AT mac DOT com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Emits a bash completion script such that typing bzfs <TAB> or bzfs_jobrunner <TAB> will auto-complete all flags.
# Usage: ./shell-completion-generator.sh > /etc/bash_completion.d/bzfs-shell-completion
# or     ./shell-completion-generator.sh > ~/.bash_completion.d/bzfs-shell-completion
set -e

# Locate the directory containing bzfs.py
cd $(realpath $(dirname "$0")/../bzfs)
export PATH=.:$PATH

# Introspect bzfs.py/argument_parser() to gather all flags
opts=$(python3 - <<EOF
import argparse
import bzfs
flags  = {
    opt
    for action in bzfs.argument_parser()._actions
    if action.help is not argparse.SUPPRESS
    for opt in action.option_strings
}
print(" ".join(sorted(flags)))
EOF
)

# Emit bash completion function
cat <<EOF
# bash completion for $(bzfs --version): typing bzfs <TAB> will auto-complete all flags.
# Usage: source bzfs-shell-completion
# This file was auto-generated by shell-completion-generator.sh

_bzfs() {
    local cur opts
    COMPREPLY=()
    cur="\${COMP_WORDS[COMP_CWORD]}"
    opts="$opts"
    COMPREPLY=( \$(compgen -W "\${opts}" -- "\${cur}") )
    return 0
}
complete -o default -o nospace -F _bzfs bzfs

EOF

# Introspect bzfs_jobrunner.py/argument_parser() to gather all flags
opts=$(python3 - <<EOF
import argparse
import bzfs_jobrunner
flags  = {
    opt
    for action in bzfs_jobrunner.argument_parser()._actions
    if action.help is not argparse.SUPPRESS
    for opt in action.option_strings
}
print(" ".join(sorted(flags)))
EOF
)

# Emit bash completion function
cat <<EOF
# bash completion for $(bzfs_jobrunner --version): typing bzfs_jobrunner <TAB> will auto-complete all flags.
# Usage: source bzfs-shell-completion
# This file was auto-generated by shell-completion-generator.sh

_bzfs_jobrunner() {
    local cur opts
    COMPREPLY=()
    cur="\${COMP_WORDS[COMP_CWORD]}"
    opts="$opts"
    COMPREPLY=( \$(compgen -W "\${opts}" -- "\${cur}") )
    return 0
}
complete -o default -o nospace -F _bzfs_jobrunner bzfs_jobrunner

EOF
