#!/usr/bin/env bash

# Copyright 2024 Wolfgang Hoschek AT mac DOT com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
PYTHONPATH="$(dirname "$(dirname "$(realpath "$0")")")"
export PYTHONPATH
export PYTHONSAFEPATH=1
export PYTHONNOUSERSITE=1
export PYTHON_LAZY_IMPORTS="${PYTHON_LAZY_IMPORTS:-all}"  # PEP 810
python_exe=python3
if [[ "${BZFS_UV_PYTHON:-}" != "" ]]; then  # e.g. '3' or '3.14' or '3.14.4'
    if ! python_exe="$(uv python find --no-project --managed-python "$BZFS_UV_PYTHON" 2> /dev/null)"; then
        uv python install "$BZFS_UV_PYTHON"
        python_exe="$(uv python find --no-project --managed-python "$BZFS_UV_PYTHON")"
    fi
fi
exec "$python_exe" -m bzfs_main.bzfs ${1+"$@"}
