#!/usr/bin/env bash

# Copyright 2024 Wolfgang Hoschek AT mac DOT com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Runs the `prettier` formatter CLI as part of pre-commit; see https://github.com/prettier/prettier
set -e
script_dir="$(dirname "$(realpath "$0")")"
repo_root="$(dirname "$script_dir")"
package_name='prettier'
package_version='3.9.6'
package_sha256='997da95cf2ae81053cafc79ef122a6e8dc12e3f2c619d57eb1f2e19525fb212f'
package_tarball_url="https://registry.npmjs.org/${package_name}/-/${package_name}-${package_version}.tgz"
# curl -fsSL "$package_tarball_url" | sha256sum -b | sed 's/[[:blank:]].*//'  # actual value of package_sha256
package_cli="$repo_root/.venv/${package_name}/${package_name}-${package_version}/package/bin/${package_name}.cjs"
if [ ! -f "$package_cli" ]; then
    "$script_dir/install_npm_package.py" "$package_name" "$package_version" "$package_tarball_url" "$package_sha256"
fi
exec node "$package_cli" ${1+"$@"}
