#!/usr/bin/env bash

# Copyright 2024 Wolfgang Hoschek AT mac DOT com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Runs the `shellcheck` CLI as part of pre-commit; see https://github.com/koalaman/shellcheck
set -e
package_cli=shellcheck
script_path="$(realpath "$0")"
script_dir="$(dirname "$script_path")"
repo_root="$(dirname "$script_dir")"
if [[ "$(uname -s)" != "Linux" && "$(uname -s)" != "Darwin" ]]; then  # install_shellcheck.py knows no binaries for FreeBSD
    if command -v "$package_cli" > /dev/null 2>&1 && [ "$(realpath "$(command -v "$package_cli")")" != "$script_path" ]; then
        exec "$package_cli" ${1+"$@"}
        exit 0
    fi
fi
"${script_dir}/install_${package_cli}.py"
package_cli="${repo_root}/.venv/bin/${package_cli}"
exec "$package_cli" ${1+"$@"}
