# bzfs Docker Compose
# Usage: sudo docker compose -f docker-compose.yml up -d

name: bzfs

services:
  bzfs:
    image: ${BZFS_DOCKER_IMAGE:-docker.io/whoschek/bzfs:v1.19.0-ubuntu-24.04}
    container_name: bzfs
    privileged: true
    restart: unless-stopped
    ports:
      - "2222:2222"  # hpnssh
    devices:
      - /dev/zfs:/dev/zfs
    volumes:
      - type: bind
        source: /etc/ssh
        target: /etc/ssh
        read_only: true
      - type: bind
        source: /etc/hpnssh
        target: /etc/hpnssh
        read_only: true
      - type: bind
        source: /bzfs.ssh
        target: /root/.ssh
        read_only: true
