# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python#publishing-to-pypi

name: Upload Package to PyPI on Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment:
      name: pypi
      url: https://pypi.org/p/bzfs
    permissions:
      id-token: write # for PyPI's trusted publishing
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # aka v6.0.2
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # aka v6.2.0
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          . ./preinstall_dev.sh
          python3 -m pip install build
      - name: Build package
        run: python3 -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # aka v1.14.0; see https://github.com/pypa/gh-action-pypi-publish
        with:
          verbose: true
