# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python#publishing-to-pypi

name: Upload Package to PyPI on Release

on:
  release:
    types: [published]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment:
      name: pypi
    permissions:
      id-token: write # for PyPI's trusted publishing
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # aka v7.0.1
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # aka v7.0.0
        with:
          python-version: 3.14
      - name: make_release
        run: |
          MAKE_RELEASE_PUBLISH=true ./.github-workflow-scripts/make_release.sh
